apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbx-genai-demo-3
  namespace: csp-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbx-genai-demo-3
  template:
    metadata:
      labels:
        app: dbx-genai-demo-3
        fargateprofile: csp-demo
    spec:
      serviceAccountName: k8py
      tolerations:
        - key: "eks.amazonaws.com/compute-type"
          operator: "Equal"
          value: "fargate"
          effect: "NoSchedule"
      containers:
        - name: dbx-genai-demo-3
          image: 635910096382.dkr.ecr.us-east-1.amazonaws.com/dbx_genai_demo_3:3-amd64
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ccloud-kafka-secrets
                  key: username
            - name: SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ccloud-kafka-secrets
                  key: password
            - name: SR_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ccloud-sr-secrets
                  key: username
            - name: SR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ccloud-sr-secrets
                  key: password
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: bedrock-secrets
                  key: password
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: bedrock-secrets
                  key: username
            - name: ENV
              value: "prod-demo"
            - name: API_HOST
              value: "http://k8s-cspdemo-dbxgenai-00512f9a4c-3f4f8e619cf617b4.elb.us-west-2.amazonaws.com"
            - name: SERVER_ADDRESS
              value: "k8s-cspdemo-dbxgenai-00512f9a4c-3f4f8e619cf617b4.elb.us-west-2.amazonaws.com"
            - name: SERVER_PORT
              value: "80"
            - name: PAPERTRAIL_URL
              valueFrom:
                secretKeyRef:
                  name: papertrail-secrets
                  key: url
            - name: PAPERTRAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: papertrail-secrets
                  key: port
            - name: BOOTSTRAP_SERVER
              valueFrom:
                secretKeyRef:
                  name: misc-secrets
                  key: bootstrap_server
            - name: IN_TOPIC
              value: "raw-data"
            - name: OUT_TOPIC
              value: "rich-data"
            - name: PAPERTRAIL_PROTOCOL
              value: "tls"
            - name: DATABRICKS_HOST
              valueFrom:
                secretKeyRef:
                  name: misc-secrets
                  key: dbx_host
            - name: DATABRICKS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: misc-secrets
                  key: dbx_token
